#pyproject.toml
[tool.pylight]
include = ["src", "tests"]
exclude = ["legacy", "migrations", "**/__pycache__"]
venv = ".venv"
venvPath = "."
typeCheckingMode = "off"

# VSCode/Pylance settings
reportMissingImports = false
reportMissingTypeStubs = false
reportGeneralTypeIssues = "none"
reportOptionalMemberAccess = "none"
reportOptionalSubscript = "none"
reportUnknownVariableType = "none"
