#ops/alertmanager.yml
global:
  resolve_timeout: 5m

route:
  receiver: main
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 2h

receivers:
- name: main
  email_configs:
  - to: "ops@example.com"
    from: "alerts@${DOMAIN}"
    smarthost: "mailhog:1025"
    require_tls: false
