#ops/prometheus.yml
global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: "dignilife_api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
